### ISSUE TITLE
My Firefox doesn't looks like your

### ISSUE THREAD

**Issue by Salvodif** [Filip-Sutkowy/blurclean-firefox-theme#9]
![image](https://github.com/user-attachments/assets/edc7d982-6ec6-4c62-843f-c5e62ed780de)

I just followed the instruction, has I said before, but the result is totally different on Firefox 133.0.3 (64-bit)

**Comment by Filip-Sutkowy** [comment]
I don't see any difference in your screenshot relative to mine, only problem is the minimize, maximize and close buttons, but those are broken on mine as well. I don't have time to fix it, if you want to fix it, then you can push changes.
